site_name: Satelix – Support utilisateur

theme:
  name: material

nav:
  - Accueil: index.md
  - ADV:
      - Création d’un BC: adv/creation-bc.md
      - BC informations libres: adv/info_supp.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

